var data = {
    "ca":
    {
        "galeriaTitle":"Galeria",
        "contTitle":"Contacte",
        "barra1":"Presentació",
        "barra2":"Galeria",
        "barra3":"Contacte",
        "contactaAnimacionTitulo":"Contacte",
        "indiceTitulo":"BENVINGUTS",
        "indicepresentacion1":"Hola, sóc Jofre,",
        "decorgomaObjetivoTitulo":"Objectiu",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":""
    },
    "es":
        {
            "galeriaTitle":"Galería",
            "contTitle":"Contáctanos",
            "barra1":"Presentación",
            "barra2":"Galería",
            "barra3":"Contacto",
            "contactaAnimacionTitulo":"Contáctanos",
            "indiceTitulo":"BIENVENIDOS",
            "indicepresentacion1":"Hola, soy Jofre,",
            "indicepresentacion2":"Me considero una persona proactiva y curiosa, a la que le gusta tener siempre algún proyecto en marcha. Esta dinámica me permite no solo poner en práctica los conocimientos adquiridos, sino también ampliar mis conocimientos y entrar en áreas de la informática que no había tocado. Ya sea desarrollando aplicaciones, investigando y probando herramientas nuevas o probando de llevar a cabo ideas que me van surgiendo, mi objetivo siempre es seguir creciendo profesionalmente y mantenerme actualizado en un campo tan amplio como lo es la informática.",
            "indicepresentacion3":"Gracias por pasaros por esta web donde subo pequeños proyectos que voy haciendo en mi tiempo libre.",
            "secondT":"Galería",
            "fourthT":"Contácto",
            "decorgomaObjetivoTitulo":"Objetivo",
            "decorgomaObjetivoP1":"El objetivo de este proyecto es crear una página web de presentación para la empresa de servicios (reparaciones, mantenimiento, pintura, etc.) de mi padre.",
            "decorgomaObjetivoP2":"Mejorar mis capacidades generales de diseño",
            "decorgomaObjetivoP3":"Su creación servirá para practicar y ampliar conocimientos sobre:",
            "decorgomaMotivacion":"Motivación",
            "decorgomaMotivacionP1":"Es un tema que me parece muy interesante",
            "decorgomaMotivacionP2":"Poner en práctica y ampliar conocimientos sobre lenguajes que ya poseo conocimientos como HTML, CSS y Javascript",
            "decorgomaMotivacionP3":"Mejorar mis capacidades de diseño y creatividad",
            "decorgomaMotivacionP4":"Encontrarme con todo tipo de problemas y errores tanto complejos como comunes con el objetivo de mejorar mis capacidades de resolución de incidencias y analítica de problemas",
            "decorgomaLinkP1":"Podéis ver la página web desde haciendo clic",
            "decorgomaLinkP2":"Si estáis interesados en alguna funcionalidad del código, podéis acceder a él haciendo clic",
            "decorgomaFunc":"Funcionalidades de interés o fuera de lo común",
            "decorgomaFuncP1":"Parallax es un efecto visual que crea una sensación de profundidad al hacer que los elementos del fondo se muevan a una velocidad diferente que los del primer plano mientras el usuario se desplaza por la página. Permite una experiencia más dinámica e inmersiva.",
            "decorgomaFuncP2":"2. Galería de imágenes",
            "decorgomaFuncP3":"Se ha creado una galería de imágenes con forma de panal de abejas para que cuadre con el logo de abeja de la empresa.",
            "decorgomaFuncP4":"Adicionalmente, se ha añadido la opción de visualizar en pantalla completa las imágenes haciendo clic encima de ellas.",
            "decorgomaFuncP5":"3. Sistema de burbujas para mostrar los servicios",
            "decorgomaFuncP6":"Una manera original y diferente que se ha desarrollado para mostrar e informar de todos los tipos de servicio que se ofrecen ha sido crear un conjunto de burbujas donde cada una de ellas representaría un servicio.",
            "decorgomaFuncP7":"Cada burbuja está formada por un descriptivo y acompañada de 2 imágenes de trabajos previos realizados del servicio que se ofrece. Las imágenes podrían expandirse al pasar el ratón por encima o verse en pantalla completa al hacer clic en ellas.",
            "decorgomaFuncP8":"4. Animaciones diversas",
            "decorgomaFuncP9":"En el apartado de 'Contáctanos', para llamar la atención y como práctica, se creó una animación del logo de la empresa con el mensaje de 'Contáctanos para más información o para presupuesto'.",
            "decorgomaFuncP10":"Para acompañar el parallax, se creó una animación que va mostrando u ocultando la información que ya no está en pantalla, así al ir deslizándose por la web, se ven los textos e imágenes deslizándose hacia abajo o hacia arriba formando una animación de mostrado u ocultado.",
            "decorgomaFuncP11":"Se crearon animaciones en textos del apartado de 'Contáctanos' con color neón al pasar el ratón por encima.",
            "decorgomaResultados":"Resultados",
            "decorgomaResultadosP1":"Imágenes:",
            "decNeteja":"Software de gestión de facturación y presupuestos",
            "decNetejaObj":"Objetivo",
            "decNetejaObjP1":"El objetivo de este proyecto es crear desde cero una aplicación de escritorio para mi madre para crear y gestionar tanto la facturación mensual como los presupuestos, clientes, contratos, gestorías y recibos. Pudiendo así no solo crear y administrar todos los puntos mencionados, sino también imprimir la información mediante plantillas.",
            "decNetejaObjP2":"Dando contexto al motivo por el cual se ha creado y realizado este proyecto, es debido a que en el pasado mi tío le creó una aplicación mediante Visual Basic a mi madre para que pudiese hacer las gestiones de su empresa. Actualmente, la tecnología ha avanzado mucho y nuevos requerimientos han surgido, al igual que hay funcionalidades que ya no necesita. La idea es crear una aplicación a medida para las necesidades de mi madre manteniendo la estética del programa antiguo.",
            "decNetejaObjP3":"La aplicación se ha hecho usando el lenguaje de programación Java y una base de datos Access.",
            "decNetejaMotiv":"Motivación",
            "decNetejaMotivP1":"Poner en práctica mis conocimientos con el lenguaje de programación Java",
            "decNetejaMotivP2":"Poner en práctica en un proyecto real y ampliar mis conocimientos de diseño y consultas de bases de datos.",
            "decNetejaMod":"Modelo de datos",
            "decNetejaModP1":"Originalmente, en el programa antiguo se usó una base de datos Access con tablas sin ninguna relación entre ellas, es decir, eran islas de datos y no tenían relación alguna entre tablas.",
            "decNetejaModP2":"Para el nuevo programa se decidió cambiar esta estructura de la base de datos y usar un modelo de datos relacional. Adicionalmente, se ha replanteado todo el modelo.",
            "decNetejaModP3":"Modelo antiguo de datos:",
            "decNetejaModP4":"Nuevo modelo de datos:",
            "decNetejaApp":"Aplicación",
            "decNetejaAppP1":"Opciones presupuestos:",
            "decNetejaAppP2":"Pantalla creación presupuestos:",
            "decNetejaAppP3":"Búsqueda presupuestos:",
            "decNetejaAppP4":"Pantalla para editar presupuestos, generar un contrato a partir del presupuesto, imprimirlo y generar un PDF o eliminarlo:",
            "decNetejaAppP5":"Opciones contrato:",
            "decNetejaAppP6":"Búsqueda contrato:",
            "decNetejaAppP7":"Pantalla para editar un contrato, activarlo/desactivarlo, e imprimirlo o generar un PDF:",
            "decNetejaAppP8":"Opciones clientes:",
            "decNetejaAppP9":"Pantalla creación cliente:",
            "decNetejaAppP10":"Búsqueda cliente:",
            "decNetejaAppP11":"Pantalla para editar clientes, eliminarlo y darlo de baja/alta:",
            "decNetejaAppP12":"Opciones gestorías:",
            "decNetejaAppP13":"Pantalla de creación de gestorías",
            "decNetejaAppP14":"Búsqueda de gestorías:",
            "decNetejaAppP15":"Pantalla para editar gestorías y eliminarlas:",
            "decNetejaAppP16":"Opciones facturación:",
            "decNetejaAppP17":"Pantalla para generar la facturación mensual a partir de los contratos activos, para consultar la facturación de otros meses y para imprimirla:",
            "decNetejaAppP18":"Pantalla para crear facturas puntuales del mes:",
            "decNetejaAppP19":"Pantalla para modificar el IVA:",
            "teseractoQueEs":"¿Que es?",
            "teseractoQueEsP1":"El teseracto o hipercubo de cuatro dimensiones es una figura geométrica que representa un cubo en un espacio de cuatro dimensiones.",
            "teseractoQueEsP2":"Aunque no podemos representarlo en 4 dimensiones, sí podemos hacernos una idea de cómo debería verse. Comúnmente, se representa como un cubo 3D dentro de otro cubo 3D.",
            "teseractoObj":"Objetivo",
            "teseractoObjP1":"El objetivo de este proyecto es recrear la representación de un teseracto en 3 dimensiones.",
            "teseractoObjP2":"Su creación servirá para practicar y ampliar conocimientos sobre geometría. El proceso de construcción me permitirá desarrollar habilidades manuales, precisión en el montaje y creatividad. También será una forma de aprender combinando teoría y práctica a través de una actividad manual.",
            "teseractoObjP3":"Otras personas ya se han planteado anteriormente la creación de un teseracto, logrando así increíbles resultados:",
            "teseractoMotiv":"Motivación",
            "teseractoMotivP1":"Es un tema que me parece muy interesante.",
            "teseractoMotivP2":"Ampliar conocimientos sobre geometría y espacios multidimensionales",
            "teseractoMotivP3":"Desarrollar habilidades manuales y de precisión en el montaje",
            "teseractoMotivP4":"Mejorar la creatividad y resolución de problemas encontrados en el desarrollo",
            "teseractoMat":"Materiales usados",
            "teseractoMatP1":"",
            "teseractoMatP2":"",
            "teseractoMatP3":"Cualquier tipo de iluminación, ya sea una pequeña bombilla, cable LED, etc. Componentes básicos para hacer que la bombilla se ilumine y poder apagarla a voluntad (interruptor, pila, portapilas, cableado, todo que ocupe el menor espacio posible)",
            "teseractoMatP4":"Loctite y cinta para su estética",
            "teseractoCom":"Comentarios y consejos",
            "teseractoComP1":"Para cortar el cristal necesitaréis usar un 'cúter' o 'bolígrafo' con punta de diamante (encontraréis muchos lugares que os lo pueden cortar).",
            "teseractoComP2":"Limpiar los cristales puede suponer la pérdida de las propiedades con efecto de reflejo en el cristal, así que NO retiréis el protector de los cristales hasta estar bien unidos y cuadrados con todas las piezas (retirar el protector debería ser el último paso).",
            "teseractoComP3":"Para mejorar la estética y poder introducir la luz interior del teseracto, lo ideal sería que la luz proviniera del interior del cubo pequeño del teseracto. Para ello, la unión de los lados de ese cubo no ha de ser perfecta, sino dejar pequeñas ranuras para que salga la luz que instalaremos en su interior. Como truco, usé varillas acrílicas para unir los lados y así dejar que la luz saliera por estas varillas.",
            "teseractoComP4":"Loctite no es el mejor pegamento para este montaje, se debería buscar una alternativa que permitiese unir varillas acrílicas con cristal, que quedase transparente y que el pegamento quedase completamente sólido.",
            "teseractoComP5":"Aunque no se ve en las imágenes, yo dejé una trampilla para poder abrir y cerrar el teseracto debido a que el interruptor lo dejé dentro por comodidad. Tened en cuenta cómo vais a suministrar electricidad para iluminar el teseracto antes de empezar la construcción.",
            "teseractoRes":"Resultados",
            "teseractoResP1":"Imágenes:",
            "teseractoResP2":"Vídeo",
            "scraperQueEs":"¿Que es?",
            "scraperQueEsP1":"Un scraper es un programa informático o una herramienta que se utiliza para extraer datos de páginas web de forma automática.",
            "scraperQueEsP2":"Funciona como un robot que simula la navegación de un usuario para recopilar información.",
            "scraperObj":"Objetivo",
            "scraperObjP1":"",
            "scraperObjP2":"Se quiere recopilar información sobre todos los personajes (nombres, edades, habilidades, apariciones…) y almacenar esta información en archivos Excel o CSV para posteriormente usarla en futuros proyectos.",
            "scraperObjP3":"El proyecto no solo va a constar de un scraper, sino que también se hará un postprocesado de los datos para limpiarlos y dejarlos con coherencia.",
            "scraperObjP4":"Su creación servirá para aprender el funcionamiento de un scraper y cómo programarlo. También será de utilidad para poner en práctica técnicas de postprocesado aprendidas en el grado universitario.",
            "scraperMotiv":"Motivación",
            "scraperMotivP1":"Aprender a programar un scraper",
            "scraperMotivP2":"Poner en práctica habilidades de postprocesado de datos",
            "scraperMotivP3":"Poner en práctica mis conocimientos en programación en Python y en librerías muy útiles como NumPy o Pandas.",
            "scraperCod":"Código",
            "scraperCodP1":"Para el desarrollo del scraper se ha usado el lenguaje de programación Python y el programa Jupyter Notebook. A continuación, vamos a ver paso a paso cómo se ha creado el scraper.",
            "scraperCodP2":"Importamos las librerías que vamos a usar:",
            "scraperCodP3":"Definimos las variables que usaremos continuamente:",
            "scraperCodP4":"Definimos el conjunto de funciones que extraerán los datos que queremos de la página web, es decir, estas funciones serán el core de nuestro scraper. Como dependiendo de la hoja que queramos extraer datos va a tener un código fuente diferente, vamos a crear múltiples funciones dependiendo de la información que queramos extraer:",
            "scraperCodP5":"La función Personajes obtendrá toda la información personal de los personajes, a excepción del Haki, Raza, Género y Categoría, debido a que su información es de difícil acceso:",
            "scraperCodP6":"La función PersonajesGenero, obtendrá el Género de todos los personajes:",
            "scraperCodP7":"La función PersonajesHaki obtendrá qué usuarios tienen haki y de qué tipo:",
            "scraperCodP8":"La función RazasPersonajes, obtendrá la Raza de cada personaje de One Piece:",
            "scraperCodP9":"Obtenemos los personajes Cannon y No Cannon y lo guardamos en Excels (lo hace la própia función):",
            "scraperCodP10":"Obtenemos el Género de todos los personajes:",
            "scraperCodP11":"Obtenemos los personajes que tienen haki y cuál, y los guardamos en Excels:",
            "scraperCodP12":"Obtenemos las Razas de los personajes, y lo guardamos en Excels:",
            "scraperCodP13":"Ahora entraremos en el tratamiento de datos y la unión de todos los datos.",
            "scraperCodP14":"Para ello primero definiremos 3 funciones para tratar las recompensas (extraer_mayor_recompensa), para tratar la edad de los personajes (extract_max_age) y el tratamiento de la altura (extraer_ultima_altura):",
            "scraperCodP15":"A continuación, vamos a leer todos los ficheros Excel y guardarlos en diferentes variables:",
            "scraperCodP16":"Ahora vamos a realizar el tratamiento de datos de los personajes No Cannon:",
            "scraperCodP17":"Ahora el tratamiento de los personajes Cannon que es igual que el de los No Cannon:",
            "scraperCodP18":"Finalmente unimos los 2 dataset con los personajes Cannon y no Cannon y creamos una columna para saber si ese personaje es Cannon o no:",
            "scraperCodP19":"Guardamos todo en un Excel:",
            "scraperCodP20":"Adicionalmente, si queremos ver un resumen general de nuestros datos, podemos hacer lo siguiente:",
            "scraperTabla":"Tabla Excel final",
            "scraperDesc":"Descarga los Excels",
            "scraperDescP1":"Excels antes del tratamiento",
            "scraperDescP2":"Excel post tratamiento",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":""
        },
    "en":
        {
            "galeriaTitle":"",
            "contTitle":"",
            "barra1":"Qui som",
            "barra2":"Que fem",
            "barra3":"",
            "contactaAnimacionTitulo":"",
            "contactaAnimacionTitulo":""
        }
}

function swapLang(lan) {
    localStorage.setItem('lang', lan);

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const text = data[lan][key];
        if (text !== undefined) {
            el.textContent = text;
        } else {
            console.warn(`Traducción no encontrada para clave: "${key}"`);
        }
    });
}

window.onload = () => {
    const savedLang = localStorage.getItem('lang') || 'es';
    swapLang(savedLang);
};

window.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem('lang') || 'es';
    swapLang(savedLang);
});