var data = {
    "ca":
        {
            "galeriaTitle":"Galeria",
            "contTitle":"Contacta'ns",
            "barra1":"Presentació",
            "barra2":"Galeria",
            "barra3":"Contacte",
            "contactaAnimacionTitulo":"Contacta'ns",
            "indiceTitulo":"BENVINGUTS",
            "indicepresentacion1":"Hola, em dic Jofre,",
            "indicepresentacion2":"Em considero una persona proactiva i curiosa, a qui li agrada tenir sempre algun projecte en marxa. Aquesta dinàmica em permet no només posar en pràctica els coneixements adquirits, sinó també ampliar els meus coneixements i entrar en àrees de la informàtica que no havia tocat. Ja sigui desenvolupant aplicacions, investigant i provant eines noves o provant de dur a terme idees que em van sorgint, el meu objectiu sempre és seguir creixent professionalment i mantenir-me actualitzat en un camp tan ampli com és la informàtica.",
            "indicepresentacion3":"Gràcies per passar-vos per aquesta web on penjo petits projectes que vaig fent en el meu temps lliure.",
            "secondT":"Galeria",
            "fourthT":"Contacte",
            "decorgomaObjetivoTitulo":"Objectiu",
            "decorgomaObjetivoP1":"L'objectiu d'aquest projecte és crear una pàgina web de presentació per a l'empresa de serveis (reparacions, manteniment, pintura, etc.) del meu pare.",
            "decorgomaObjetivoP2":"Millorar les meves capacitats generals de disseny",
            "decorgomaObjetivoP3":"La seva creació servirà per practicar i ampliar coneixements sobre:",
            "decorgomaMotivacion":"Motivació",
            "decorgomaMotivacionP1":"És un tema que em sembla molt interessant",
            "decorgomaMotivacionP2":"Posar en pràctica i ampliar coneixements sobre llenguatges que ja conec com HTML, CSS i Javascript",
            "decorgomaMotivacionP3":"Millorar les meves capacitats de disseny i creativitat",
            "decorgomaMotivacionP4":"Enfrontar-me a tot tipus de problemes i errors tant complexos com comuns amb l'objectiu de millorar les meves capacitats de resolució d'incidències i anàlisi de problemes",
            "decorgomaLinkP1":"Podeu veure la pàgina web fent clic ",
            "decorgomaLinkP2":"Si esteu interessats en alguna funcionalitat del codi, podeu accedir-hi fent clic ",
            "decorgomaFunc":"Funcionalitats d'interès o fora del comú",
            "decorgomaFuncP1":"Parallax és un efecte visual que crea una sensació de profunditat fent que els elements del fons es moguin a una velocitat diferent dels del primer pla mentre l'usuari es desplaça per la pàgina. Permet una experiència més dinàmica i immersiva.",
            "decorgomaFuncP2":"2. Galeria d'imatges",
            "decorgomaFuncP3":"S'ha creat una galeria d'imatges amb forma de panal d'abelles per a que quadri amb el logo d'abella de l'empresa.",
            "decorgomaFuncP4":"Addicionalment, s'ha afegit l'opció de visualitzar a pantalla completa les imatges fent clic sobre elles.",
            "decorgomaFuncP5":"3. Sistema de bombolles per mostrar els serveis",
            "decorgomaFuncP6":"Una manera original i diferent que s'ha desenvolupat per mostrar i informar de tots els tipus de servei que s'ofereixen ha estat crear un conjunt de bombolles on cadascuna representa un servei.",
            "decorgomaFuncP7":"Cada bombolla està formada per un descriptiu i acompanyada de 2 imatges de treballs previs realitzats del servei que s'ofereix. Les imatges podrien expandir-se passant el ratolí per sobre o veure's a pantalla completa fent clic en elles.",
            "decorgomaFuncP8":"4. Animacions diverses",
            "decorgomaFuncP9":"A l'apartat de 'Contacta'ns', per cridar l'atenció i com a pràctica, es va crear una animació del logo de l'empresa amb el missatge de 'Contacta'ns per més informació o per pressupost'.",
            "decorgomaFuncP10":"Per acompanyar el parallax, es va crear una animació que va mostrant o amagant la informació que ja no està a pantalla, així en desplaçar-se per la web, es veuen els textos i imatges lliscant cap avall o cap amunt formant una animació de mostrar o amagar.",
            "decorgomaFuncP11":"Es van crear animacions en textos de l'apartat de 'Contacta'ns' amb color neó passant el ratolí per sobre.",
            "decorgomaResultados":"Resultats",
            "decorgomaResultadosP1":"Imatges:",
            "decNeteja":"Software de gestió de facturació i pressupostos",
            "decNetejaObj":"Objectiu",
            "decNetejaObjP1":"L'objectiu d'aquest projecte és crear des de zero una aplicació d'escriptori per a la meva mare per crear i gestionar tant la facturació mensual com els pressupostos, clients, contractes, gestoríes i rebuts. Podent així no només crear i administrar tots els punts esmentats, sinó també imprimir la informació mitjançant plantilles.",
            "decNetejaObjP2":"Donant context al motiu pel qual s'ha creat i realitzat aquest projecte, és degut a que en el passat el meu tiet li va crear una aplicació mitjançant Visual Basic a la meva mare perquè pogués fer les gestions de la seva empresa. Actualment, la tecnologia ha avançat molt i han sorgit nous requeriments, així com funcionalitats que ja no necessita. La idea és crear una aplicació a mida per a les necessitats de la meva mare mantenint l'estètica del programa antic.",
            "decNetejaObjP3":"L'aplicació s'ha desenvolupat mitjançant el llenguatge de programació Java i una base de dades Access.",
            "decNetejaMotiv":"Motivació",
            "decNetejaMotivP1":"Posar en pràctica els meus coneixements amb el llenguatge de programació Java",
            "decNetejaMotivP2":"Posar en pràctica en un projecte real i ampliar els meus coneixements de disseny i consultes de bases de dades.",
            "decNetejaMod":"Model de dades",
            "decNetejaModP1":"Originalment, en el programa antic es va utilitzar una base de dades Access amb taules sense cap relació entre elles, és a dir, eren illes de dades i no tenien cap relació entre taules.",
            "decNetejaModP2":"Per al nou programa es va decidir canviar aquesta estructura de la base de dades i usar un model de dades relacional. Addicionalment, s'ha replantejat tot el model.",
            "decNetejaModP3":"Model antic de dades:",
            "decNetejaModP4":"Nou model de dades:",
            "decNetejaApp":"Aplicació",
            "decNetejaAppP1":"Opcions pressupostos:",
            "decNetejaAppP2":"Pantalla creació pressupostos:",
            "decNetejaAppP3":"Cerca pressupostos:",
            "decNetejaAppP4":"Pantalla per editar pressupostos, generar un contracte a partir del pressupost, imprimir-lo i generar un PDF o eliminar-lo:",
            "decNetejaAppP5":"Opcions contracte:",
            "decNetejaAppP6":"Cerca contracte:",
            "decNetejaAppP7":"Pantalla per editar un contracte, activar/desactivar-lo, i imprimir-lo o generar un PDF:",
            "decNetejaAppP8":"Opcions clients:",
            "decNetejaAppP9":"Pantalla creació client:",
            "decNetejaAppP10":"Cerca client:",
            "decNetejaAppP11":"Pantalla per editar clients, eliminar-lo i donar-lo de baixa/alta:",
            "decNetejaAppP12":"Opcions gestoríes:",
            "decNetejaAppP13":"Pantalla de creació de gestoríes",
            "decNetejaAppP14":"Cerca de gestoríes:",
            "decNetejaAppP15":"Pantalla per editar gestoríes i eliminar-les:",
            "decNetejaAppP16":"Opcions facturació:",
            "decNetejaAppP17":"Pantalla per generar la facturació mensual a partir dels contractes actius, per consultar la facturació d'altres mesos i per imprimir-la:",
            "decNetejaAppP18":"Pantalla per crear factures puntuals del mes:",
            "decNetejaAppP19":"Pantalla per modificar l'IVA:",
            "teseractoQueEs":"Què és?",
            "teseractoQueEsP1":"El tesseracte o hipercub de quatre dimensions és una figura geomètrica que representa un cub en un espai de quatre dimensions.",
            "teseractoQueEsP2":"Tot i que no podem representar-lo en 4 dimensions, sí que ens podem fer una idea de com hauria de veure's. Comúment, es representa com un cub 3D dins d'un altre cub 3D.",
            "teseractoObj":"Objectiu",
            "teseractoObjP1":"L'objectiu d'aquest projecte és recrear la representació d'un tesseracte en 3 dimensions.",
            "teseractoObjP2":"La seva creació servirà per practicar i ampliar coneixements sobre geometria. El procés de construcció em permetrà desenvolupar habilitats manuals, precisió en el muntatge i creativitat. També serà una manera d'aprendre combinant teoria i pràctica a través d'una activitat manual.",
            "teseractoObjP3":"Altres persones ja s'han plantejat anteriorment la creació d'un tesseracte, aconseguint així resultats increïbles:",
            "teseractoMotiv":"Motivació",
            "teseractoMotivP1":"És un tema que em sembla molt interessant.",
            "teseractoMotivP2":"Ampliar coneixements sobre geometria i espais multidimensionals",
            "teseractoMotivP3":"Desenvolupar habilitats manuals i de precisió en el muntatge",
            "teseractoMotivP4":"Millorar la creativitat i resolució de problemes trobats en el desenvolupament",
            "teseractoMat":"Materials utilitzats",
            "teseractoMatP1":"",
            "teseractoMatP2":"",
            "teseractoMatP3": "Qualsevol tipus d'il·luminació, sigui una petita bombeta, cable LED, etc. Components bàsics per fer que la bombeta s'il·lumini i poder apagar-la a voluntat (interruptor, pila, portapiles, cablejat, tot el que ocupi el menor espai possible)",
            "teseractoMatP4": "Loctite i cinta per a la seva estètica",
            "teseractoCom": "Comentaris i consells",
            "teseractoComP1": "Per tallar el vidre necessitareu utilitzar un 'cúter' o 'bolígraf' amb punta de diamant (trobareu molts llocs que us el poden tallar).",
            "teseractoComP2": "Netejar els vidres pot suposar la pèrdua de les propietats amb efecte de reflex en el vidre, així que NO retireu el protector dels vidres fins a estar ben units i quadrats amb totes les peces (retirar el protector hauria de ser l'últim pas).",
            "teseractoComP3": "Per millorar l'estètica i poder introduir la llum interior del teseracte, l'ideal seria que la llum provingués de l'interior del cub petit del teseracte. Per això, la unió dels costats d'aquest cub no ha de ser perfecta, sinó deixar petites ranures perquè surti la llum que instal·larem al seu interior. Com a truc, vaig usar varetes acríliques per unir els costats i així deixar que la llum sortís per aquestes varetes.",
            "teseractoComP4": "Loctite no és el millor adhesiu per a aquest muntatge, s'hauria de buscar una alternativa que permetés unir varetes acríliques amb vidre, que quedés transparent i que l'adhesiu quedés completament sòlid.",
            "teseractoComP5": "Tot i que no es veu a les imatges, jo vaig deixar una trampilla per poder obrir i tancar el teseracte degut a que l'interruptor el vaig deixar dins per comoditat. Tingueu en compte com proveireu electricitat per il·luminar el teseracte abans de començar la construcció.",
            "teseractoRes": "Resultats",
            "teseractoResP1": "Imatges:",
            "teseractoResP2": "Vídeo",
            "scraperQueEs": "Què és?",
            "scraperQueEsP1": "Un scraper és un programa informàtic o una eina que s'utilitza per extreure dades de pàgines web de forma automàtica.",
            "scraperQueEsP2": "Funciona com un robot que simula la navegació d'un usuari per recopilar informació.",
            "scraperObj": "Objectiu",
            "scraperObjP1": "L'objectiu d'aquest projecte és crear un scraper per la web ",
            "scraperObjP2": "Es vol recopilar informació sobre tots els personatges (noms, edats, habilitats, aparicions...) i emmagatzemar aquesta informació en fitxers Excel o CSV per utilitzar-la posteriorment en futurs projectes.",
            "scraperObjP3": "El projecte no només constarà d'un scraper, sinó que també es farà un postprocessat de les dades per netejar-les i deixar-les coherents.",
            "scraperObjP4": "La seva creació servirà per aprendre el funcionament d'un scraper i com programar-lo. També serà útil per posar en pràctica tècniques de postprocessat apreses en el grau universitari.",
            "scraperMotiv": "Motivació",
            "scraperMotivP1": "Aprendre a programar un scraper",
            "scraperMotivP2": "Posar en pràctica habilitats de postprocessat de dades",
            "scraperMotivP3": "Posar en pràctica els meus coneixements en programació en Python i en llibreries molt útils com NumPy o Pandas.",
            "scraperCod": "Codi",
            "scraperCodP1": "Per al desenvolupament del scraper s'ha utilitzat el llenguatge de programació Python i el programa Jupyter Notebook. A continuació, veurem pas a pas com s'ha creat el scraper.",
            "scraperCodP2": "Importem les llibreries que farem servir:",
            "scraperCodP3": "Definim les variables que utilitzarem contínuament:",
            "scraperCodP4": "Definim el conjunt de funcions que extreuràn les dades que volem de la pàgina web, és a dir, aquestes funcions seran el nucli del nostre scraper. Com que depenent de la pàgina que vulguem extreure dades tindrà un codi font diferent, crearem múltiples funcions depenent de la informació que volem extreure:",
            "scraperCodP5": "La funció Personatges obtindrà tota la informació personal dels personatges, excepte l'Haki, Raça, Gènere i Categoria, ja que la seva informació és de difícil accés:",
            "scraperCodP6": "La funció PersonatgesGenere, obtindrà el Gènere de tots els personatges:",
            "scraperCodP7": "La funció PersonatgesHaki obtindrà quins usuaris tenen haki i de quin tipus:",
            "scraperCodP8": "La funció RacesPersonatges, obtindrà la Raça de cada personatge de One Piece:",
            "scraperCodP9": "Obtenim els personatges Canon i No Canon i ho guardem en Excels (ho fa la pròpia funció):",
            "scraperCodP10": "Obtenim el Gènere de tots els personatges:",
            "scraperCodP11": "Obtenim els personatges que tenen haki i quin, i els guardem en Excels:",
            "scraperCodP12": "Obtenim les Races dels personatges, i ho guardem en Excels:",
            "scraperCodP13": "Ara entrarem en el tractament de dades i la unió de totes les dades.",
            "scraperCodP14": "Per això primer definirem 3 funcions per tractar les recompenses (extreure_major_recompensa), per tractar l'edat dels personatges (extreure_max_edat) i el tractament de l'alçada (extreure_ultima_alçada):",
            "scraperCodP15": "A continuació, llegirem tots els fitxers Excel i els guardarem en diferents variables:",
            "scraperCodP16": "Ara farem el tractament de dades dels personatges No Canon:",
            "scraperCodP17": "Ara el tractament dels personatges Canon que és igual que el dels No Canon:",
            "scraperCodP18": "Finalment unim els 2 datasets amb els personatges Canon i no Canon i creem una columna per saber si aquest personatge és Canon o no:",
            "scraperCodP19": "Guardem tot en un Excel:",
            "scraperCodP20": "Addicionalment, si volem veure un resum general de les nostres dades, podem fer el següent:",
            "scraperTabla": "Taula Excel final",
            "scraperDesc": "Descarrega els Excels",
            "scraperDescP1": "Excels abans del tractament",
            "scraperDescP2": "Excel post tractament",
            "scraperTitol":"Scraper per web de One Piece"
        },
    "es":
        {
            "galeriaTitle":"Galería",
            "contTitle":"Contáctanos",
            "barra1":"Presentación",
            "barra2":"Galería",
            "barra3":"Contacto",
            "contactaAnimacionTitulo":"Contáctanos",
            "indiceTitulo":"BIENVENIDOS",
            "indicepresentacion1":"Hola, soy Jofre,",
            "indicepresentacion2":"Me considero una persona proactiva y curiosa, a la que le gusta tener siempre algún proyecto en marcha. Esta dinámica me permite no solo poner en práctica los conocimientos adquiridos, sino también ampliar mis conocimientos y entrar en áreas de la informática que no había tocado. Ya sea desarrollando aplicaciones, investigando y probando herramientas nuevas o probando de llevar a cabo ideas que me van surgiendo, mi objetivo siempre es seguir creciendo profesionalmente y mantenerme actualizado en un campo tan amplio como lo es la informática.",
            "indicepresentacion3":"Gracias por pasaros por esta web donde subo pequeños proyectos que voy haciendo en mi tiempo libre.",
            "secondT":"Galería",
            "fourthT":"Contácto",
            "decorgomaObjetivoTitulo":"Objetivo",
            "decorgomaObjetivoP1":"El objetivo de este proyecto es crear una página web de presentación para la empresa de servicios (reparaciones, mantenimiento, pintura, etc.) de mi padre.",
            "decorgomaObjetivoP2":"Mejorar mis capacidades generales de diseño",
            "decorgomaObjetivoP3":"Su creación servirá para practicar y ampliar conocimientos sobre:",
            "decorgomaMotivacion":"Motivación",
            "decorgomaMotivacionP1":"Es un tema que me parece muy interesante",
            "decorgomaMotivacionP2":"Poner en práctica y ampliar conocimientos sobre lenguajes que ya poseo conocimientos como HTML, CSS y Javascript",
            "decorgomaMotivacionP3":"Mejorar mis capacidades de diseño y creatividad",
            "decorgomaMotivacionP4":"Encontrarme con todo tipo de problemas y errores tanto complejos como comunes con el objetivo de mejorar mis capacidades de resolución de incidencias y analítica de problemas",
            "decorgomaLinkP1":"Podéis ver la página web desde haciendo clic ",
            "decorgomaLinkP2":"Si estáis interesados en alguna funcionalidad del código, podéis acceder a él haciendo clic ",
            "decorgomaFunc":"Funcionalidades de interés o fuera de lo común",
            "decorgomaFuncP1":"Parallax es un efecto visual que crea una sensación de profundidad al hacer que los elementos del fondo se muevan a una velocidad diferente que los del primer plano mientras el usuario se desplaza por la página. Permite una experiencia más dinámica e inmersiva.",
            "decorgomaFuncP2":"2. Galería de imágenes",
            "decorgomaFuncP3":"Se ha creado una galería de imágenes con forma de panal de abejas para que cuadre con el logo de abeja de la empresa.",
            "decorgomaFuncP4":"Adicionalmente, se ha añadido la opción de visualizar en pantalla completa las imágenes haciendo clic encima de ellas.",
            "decorgomaFuncP5":"3. Sistema de burbujas para mostrar los servicios",
            "decorgomaFuncP6":"Una manera original y diferente que se ha desarrollado para mostrar e informar de todos los tipos de servicio que se ofrecen ha sido crear un conjunto de burbujas donde cada una de ellas representaría un servicio.",
            "decorgomaFuncP7":"Cada burbuja está formada por un descriptivo y acompañada de 2 imágenes de trabajos previos realizados del servicio que se ofrece. Las imágenes podrían expandirse al pasar el ratón por encima o verse en pantalla completa al hacer clic en ellas.",
            "decorgomaFuncP8":"4. Animaciones diversas",
            "decorgomaFuncP9":"En el apartado de 'Contáctanos', para llamar la atención y como práctica, se creó una animación del logo de la empresa con el mensaje de 'Contáctanos para más información o para presupuesto'.",
            "decorgomaFuncP10":"Para acompañar el parallax, se creó una animación que va mostrando u ocultando la información que ya no está en pantalla, así al ir deslizándose por la web, se ven los textos e imágenes deslizándose hacia abajo o hacia arriba formando una animación de mostrado u ocultado.",
            "decorgomaFuncP11":"Se crearon animaciones en textos del apartado de 'Contáctanos' con color neón al pasar el ratón por encima.",
            "decorgomaResultados":"Resultados",
            "decorgomaResultadosP1":"Imágenes:",
            "decNeteja":"Software de gestión de facturación y presupuestos",
            "decNetejaObj":"Objetivo",
            "decNetejaObjP1":"El objetivo de este proyecto es crear desde cero una aplicación de escritorio para mi madre para crear y gestionar tanto la facturación mensual como los presupuestos, clientes, contratos, gestorías y recibos. Pudiendo así no solo crear y administrar todos los puntos mencionados, sino también imprimir la información mediante plantillas.",
            "decNetejaObjP2":"Dando contexto al motivo por el cual se ha creado y realizado este proyecto, es debido a que en el pasado mi tío le creó una aplicación mediante Visual Basic a mi madre para que pudiese hacer las gestiones de su empresa. Actualmente, la tecnología ha avanzado mucho y nuevos requerimientos han surgido, al igual que hay funcionalidades que ya no necesita. La idea es crear una aplicación a medida para las necesidades de mi madre manteniendo la estética del programa antiguo.",
            "decNetejaObjP3":"La aplicación se ha hecho usando el lenguaje de programación Java y una base de datos Access.",
            "decNetejaMotiv":"Motivación",
            "decNetejaMotivP1":"Poner en práctica mis conocimientos con el lenguaje de programación Java",
            "decNetejaMotivP2":"Poner en práctica en un proyecto real y ampliar mis conocimientos de diseño y consultas de bases de datos.",
            "decNetejaMod":"Modelo de datos",
            "decNetejaModP1":"Originalmente, en el programa antiguo se usó una base de datos Access con tablas sin ninguna relación entre ellas, es decir, eran islas de datos y no tenían relación alguna entre tablas.",
            "decNetejaModP2":"Para el nuevo programa se decidió cambiar esta estructura de la base de datos y usar un modelo de datos relacional. Adicionalmente, se ha replanteado todo el modelo.",
            "decNetejaModP3":"Modelo antiguo de datos:",
            "decNetejaModP4":"Nuevo modelo de datos:",
            "decNetejaApp":"Aplicación",
            "decNetejaAppP1":"Opciones presupuestos:",
            "decNetejaAppP2":"Pantalla creación presupuestos:",
            "decNetejaAppP3":"Búsqueda presupuestos:",
            "decNetejaAppP4":"Pantalla para editar presupuestos, generar un contrato a partir del presupuesto, imprimirlo y generar un PDF o eliminarlo:",
            "decNetejaAppP5":"Opciones contrato:",
            "decNetejaAppP6":"Búsqueda contrato:",
            "decNetejaAppP7":"Pantalla para editar un contrato, activarlo/desactivarlo, e imprimirlo o generar un PDF:",
            "decNetejaAppP8":"Opciones clientes:",
            "decNetejaAppP9":"Pantalla creación cliente:",
            "decNetejaAppP10":"Búsqueda cliente:",
            "decNetejaAppP11":"Pantalla para editar clientes, eliminarlo y darlo de baja/alta:",
            "decNetejaAppP12":"Opciones gestorías:",
            "decNetejaAppP13":"Pantalla de creación de gestorías",
            "decNetejaAppP14":"Búsqueda de gestorías:",
            "decNetejaAppP15":"Pantalla para editar gestorías y eliminarlas:",
            "decNetejaAppP16":"Opciones facturación:",
            "decNetejaAppP17":"Pantalla para generar la facturación mensual a partir de los contratos activos, para consultar la facturación de otros meses y para imprimirla:",
            "decNetejaAppP18":"Pantalla para crear facturas puntuales del mes:",
            "decNetejaAppP19":"Pantalla para modificar el IVA:",
            "teseractoQueEs":"¿Que es?",
            "teseractoQueEsP1":"El teseracto o hipercubo de cuatro dimensiones es una figura geométrica que representa un cubo en un espacio de cuatro dimensiones.",
            "teseractoQueEsP2":"Aunque no podemos representarlo en 4 dimensiones, sí podemos hacernos una idea de cómo debería verse. Comúnmente, se representa como un cubo 3D dentro de otro cubo 3D.",
            "teseractoObj":"Objetivo",
            "teseractoObjP1":"El objetivo de este proyecto es recrear la representación de un teseracto en 3 dimensiones.",
            "teseractoObjP2":"Su creación servirá para practicar y ampliar conocimientos sobre geometría. El proceso de construcción me permitirá desarrollar habilidades manuales, precisión en el montaje y creatividad. También será una forma de aprender combinando teoría y práctica a través de una actividad manual.",
            "teseractoObjP3":"Otras personas ya se han planteado anteriormente la creación de un teseracto, logrando así increíbles resultados:",
            "teseractoMotiv":"Motivación",
            "teseractoMotivP1":"Es un tema que me parece muy interesante.",
            "teseractoMotivP2":"Ampliar conocimientos sobre geometría y espacios multidimensionales",
            "teseractoMotivP3":"Desarrollar habilidades manuales y de precisión en el montaje",
            "teseractoMotivP4":"Mejorar la creatividad y resolución de problemas encontrados en el desarrollo",
            "teseractoMat":"Materiales usados",
            "teseractoMatP1":"",
            "teseractoMatP2":"",
            "teseractoMatP3":"Cualquier tipo de iluminación, ya sea una pequeña bombilla, cable LED, etc. Componentes básicos para hacer que la bombilla se ilumine y poder apagarla a voluntad (interruptor, pila, portapilas, cableado, todo que ocupe el menor espacio posible)",
            "teseractoMatP4":"Loctite y cinta para su estética",
            "teseractoCom":"Comentarios y consejos",
            "teseractoComP1":"Para cortar el cristal necesitaréis usar un 'cúter' o 'bolígrafo' con punta de diamante (encontraréis muchos lugares que os lo pueden cortar).",
            "teseractoComP2":"Limpiar los cristales puede suponer la pérdida de las propiedades con efecto de reflejo en el cristal, así que NO retiréis el protector de los cristales hasta estar bien unidos y cuadrados con todas las piezas (retirar el protector debería ser el último paso).",
            "teseractoComP3":"Para mejorar la estética y poder introducir la luz interior del teseracto, lo ideal sería que la luz proviniera del interior del cubo pequeño del teseracto. Para ello, la unión de los lados de ese cubo no ha de ser perfecta, sino dejar pequeñas ranuras para que salga la luz que instalaremos en su interior. Como truco, usé varillas acrílicas para unir los lados y así dejar que la luz saliera por estas varillas.",
            "teseractoComP4":"Loctite no es el mejor pegamento para este montaje, se debería buscar una alternativa que permitiese unir varillas acrílicas con cristal, que quedase transparente y que el pegamento quedase completamente sólido.",
            "teseractoComP5":"Aunque no se ve en las imágenes, yo dejé una trampilla para poder abrir y cerrar el teseracto debido a que el interruptor lo dejé dentro por comodidad. Tened en cuenta cómo vais a suministrar electricidad para iluminar el teseracto antes de empezar la construcción.",
            "teseractoRes":"Resultados",
            "teseractoResP1":"Imágenes:",
            "teseractoResP2":"Vídeo",
            "scraperQueEs":"¿Que es?",
            "scraperQueEsP1":"Un scraper es un programa informático o una herramienta que se utiliza para extraer datos de páginas web de forma automática.",
            "scraperQueEsP2":"Funciona como un robot que simula la navegación de un usuario para recopilar información.",
            "scraperObj":"Objetivo",
            "scraperObjP1":"El objetivo de éste proyecto es crear un scraper para la web ",
            "scraperObjP2":"Se quiere recopilar información sobre todos los personajes (nombres, edades, habilidades, apariciones…) y almacenar esta información en archivos Excel o CSV para posteriormente usarla en futuros proyectos.",
            "scraperObjP3":"El proyecto no solo va a constar de un scraper, sino que también se hará un postprocesado de los datos para limpiarlos y dejarlos con coherencia.",
            "scraperObjP4":"Su creación servirá para aprender el funcionamiento de un scraper y cómo programarlo. También será de utilidad para poner en práctica técnicas de postprocesado aprendidas en el grado universitario.",
            "scraperMotiv":"Motivación",
            "scraperMotivP1":"Aprender a programar un scraper",
            "scraperMotivP2":"Poner en práctica habilidades de postprocesado de datos",
            "scraperMotivP3":"Poner en práctica mis conocimientos en programación en Python y en librerías muy útiles como NumPy o Pandas.",
            "scraperCod":"Código",
            "scraperCodP1":"Para el desarrollo del scraper se ha usado el lenguaje de programación Python y el programa Jupyter Notebook. A continuación, vamos a ver paso a paso cómo se ha creado el scraper.",
            "scraperCodP2":"Importamos las librerías que vamos a usar:",
            "scraperCodP3":"Definimos las variables que usaremos continuamente:",
            "scraperCodP4":"Definimos el conjunto de funciones que extraerán los datos que queremos de la página web, es decir, estas funciones serán el core de nuestro scraper. Como dependiendo de la hoja que queramos extraer datos va a tener un código fuente diferente, vamos a crear múltiples funciones dependiendo de la información que queramos extraer:",
            "scraperCodP5":"La función Personajes obtendrá toda la información personal de los personajes, a excepción del Haki, Raza, Género y Categoría, debido a que su información es de difícil acceso:",
            "scraperCodP6":"La función PersonajesGenero, obtendrá el Género de todos los personajes:",
            "scraperCodP7":"La función PersonajesHaki obtendrá qué usuarios tienen haki y de qué tipo:",
            "scraperCodP8":"La función RazasPersonajes, obtendrá la Raza de cada personaje de One Piece:",
            "scraperCodP9":"Obtenemos los personajes Cannon y No Cannon y lo guardamos en Excels (lo hace la própia función):",
            "scraperCodP10":"Obtenemos el Género de todos los personajes:",
            "scraperCodP11":"Obtenemos los personajes que tienen haki y cuál, y los guardamos en Excels:",
            "scraperCodP12":"Obtenemos las Razas de los personajes, y lo guardamos en Excels:",
            "scraperCodP13":"Ahora entraremos en el tratamiento de datos y la unión de todos los datos.",
            "scraperCodP14":"Para ello primero definiremos 3 funciones para tratar las recompensas (extraer_mayor_recompensa), para tratar la edad de los personajes (extract_max_age) y el tratamiento de la altura (extraer_ultima_altura):",
            "scraperCodP15":"A continuación, vamos a leer todos los ficheros Excel y guardarlos en diferentes variables:",
            "scraperCodP16":"Ahora vamos a realizar el tratamiento de datos de los personajes No Cannon:",
            "scraperCodP17":"Ahora el tratamiento de los personajes Cannon que es igual que el de los No Cannon:",
            "scraperCodP18":"Finalmente unimos los 2 dataset con los personajes Cannon y no Cannon y creamos una columna para saber si ese personaje es Cannon o no:",
            "scraperCodP19":"Guardamos todo en un Excel:",
            "scraperCodP20":"Adicionalmente, si queremos ver un resumen general de nuestros datos, podemos hacer lo siguiente:",
            "scraperTabla":"Tabla Excel final",
            "scraperDesc":"Descarga los Excels",
            "scraperDescP1":"Excels antes del tratamiento",
            "scraperDescP2":"Excel post tratamiento",
            "scraperTitol":"Scraper para web de One Piece",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":""
        },
    "en":
        {
            "galeriaTitle":"",
            "contTitle":"",
            "barra1":"Qui som",
            "barra2":"Que fem",
            "barra3":"",
            "contactaAnimacionTitulo":"",
            "contactaAnimacionTitulo":""
        }
}

function swapLang(lan) {
    localStorage.setItem('lang', lan);

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const text = data[lan][key];
        if (text !== undefined) {
            el.textContent = text;
        } else {
            console.warn(`Traducción no encontrada para clave: "${key}"`);
        }
    });
}

window.onload = () => {
    const savedLang = localStorage.getItem('lang') || 'es';
    swapLang(savedLang);
};

window.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem('lang') || 'es';
    swapLang(savedLang);
});