var data = {
    "ca":
    {
        "galeriaTitle":"Galeria",
        "contTitle":"Contacte",
        "barra1":"Presentació",
        "barra2":"Galeria",
        "barra3":"Contacte",
        "contactaAnimacionTitulo":"Contacte",
        "indiceTitulo":"BENVINGUTS",
        "":"Hola, sóc Jofre,",
        "decorgomaObjetivoTitulo":"Objectiu",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":"",
        "":""
    },
    "es":
        {
            "galeriaTitle":"Galería",
            "contTitle":"Contáctanos",
            "barra1":"Presentación",
            "barra2":"Galería",
            "barra3":"Contacto",
            "contactaAnimacionTitulo":"Contáctanos",
            "indiceTitulo":"BIENVENIDOS",
            "indicepresentacion1":"Hola, soy Jofre,",
            "indicepresentacion2":"Me considero una persona proactiva y curiosa, a la que le gusta tener siempre algún proyecto en marcha. Esta dinámica me permite no solo poner en práctica los conocimientos adquiridos, sino también ampliar mis conocimientos y entrar en áreas de la informática que no había tocado. Ya sea desarrollando aplicaciones, investigando y probando herramientas nuevas o probando de llevar a cabo ideas que me van surgiendo, mi objetivo siempre es seguir creciendo profesionalmente y mantenerme actualizado en un campo tan amplio como lo es la informática.",
            "indicepresentacion3":"Gracias por pasaros por esta web donde subo pequeños proyectos que voy haciendo en mi tiempo libre.",
            "secondT":"Galería",
            "fourthT":"Contácto",
            "decorgomaObjetivoTitulo":"Objetivo",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":"",
            "":""
        },
    "en":
        {
            "galeriaTitle":"",
            "contTitle":"",
            "barra1":"Qui som",
            "barra2":"Que fem",
            "barra3":"",
            "contactaAnimacionTitulo":"",
            "contactaAnimacionTitulo":""
        }
}

function swapLang(lan){
    localStorage.setItem('lang', lan);

    document.querySelector('#barra1').textContent = data[lan].barra1;
    document.querySelector('#barra2').textContent = data[lan].barra2;
    document.querySelector('#barra3').textContent = data[lan].barra3;
    document.querySelector('#indiceTitulo').textContent = data[lan].indiceTitulo;
    document.querySelector('#decorgomaObjetivoTitulo').textContent = data[lan].decorgomaObjetivoTitulo;
}

window.addEventListener("DOMContentLoaded", () => {
    console.log("Idioma cargado");
    const savedLang = localStorage.getItem('lang') || 'es';
    swapLang(savedLang);
});